<?php defined('PREVENT_DIRECT_ACCESS') OR exit('No direct script access allowed'); $editing = !empty($product); ?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $editing ? 'Edit' : 'Add' ?> product</title>
<style>:root{--ink:#3f2433;--muted:#8a6074;--accent:#e83e8c;--paper:#fff1f7;--line:#f3b6d2}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 10%,#f7a8ca 0,transparent 30%),var(--paper);color:var(--ink);font:16px/1.5 Georgia,serif}main{width:min(680px,calc(100% - 2rem));margin:4rem auto;padding:2rem;background:#fffafd;border:1px solid var(--line);box-shadow:12px 12px 0 #edb4ce}h1{margin-top:0}label{display:block;margin:1rem 0 .35rem;font-weight:700}input,textarea{width:100%;padding:.75rem;border:1px solid var(--line);font:inherit;background:#fff}textarea{min-height:130px;resize:vertical}.actions{display:flex;gap:.75rem;margin-top:1.5rem}.button,button{padding:.7rem 1rem;border:1px solid var(--accent);background:var(--accent);color:#fff;font:inherit;cursor:pointer;text-decoration:none}.button{background:transparent;color:var(--accent)}</style></head>
<body><main><h1><?= $editing ? 'Edit product' : 'Add product' ?></h1><form method="post" action="<?= htmlspecialchars($form_action, ENT_QUOTES, 'UTF-8') ?>">
<label for="product_name">Product name</label><input id="product_name" name="product_name" maxlength="100" required value="<?= htmlspecialchars($product->product_name ?? '', ENT_QUOTES, 'UTF-8') ?>">
<label for="description">Description</label><textarea id="description" name="description"><?= htmlspecialchars($product->description ?? '', ENT_QUOTES, 'UTF-8') ?></textarea>
<label for="price">Price</label><input id="price" name="price" type="number" min="0" step="0.01" required value="<?= htmlspecialchars($product->price ?? '', ENT_QUOTES, 'UTF-8') ?>">
<label for="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="0" required value="<?= (int) ($product->quantity ?? 0) ?>">
<div class="actions"><button type="submit"><?= $editing ? 'Save changes' : 'Create product' ?></button><a class="button" href="/products">Cancel</a></div></form></main></body></html>